name: healthy_pet_app
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope/Manrope-Regular.ttf
        - asset: assets/fonts/manrope/Manrope-Bold.ttf
        - asset: assets/fonts/manrope/Manrope-ExtraBold.ttf
        - asset: assets/fonts/manrope/Manrope-ExtraLight.ttf
        - asset: assets/fonts/manrope/Manrope-Light.ttf
        - asset: assets/fonts/manrope/Manrope-Medium.ttf
        - asset: assets/fonts/manrope/Manrope-SemiBold.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
